"use client";

import { useEffect, useState } from "react";
import QRCode from "qrcode";

/**
 * Renders a real, scannable QR code as inline SVG (crisp at any size — ideal
 * for both screen preview and thermal printing).
 */
export function QrCode({
  value,
  size = 120,
  className = "",
}: {
  value: string;
  size?: number;
  className?: string;
}) {
  const [svg, setSvg] = useState("");

  useEffect(() => {
    let active = true;
    QRCode.toString(value, {
      type: "svg",
      margin: 0,
      errorCorrectionLevel: "M",
      color: { dark: "#000000", light: "#ffffff" },
    })
      .then((out) => {
        if (active) setSvg(out);
      })
      .catch(() => {
        if (active) setSvg("");
      });
    return () => {
      active = false;
    };
  }, [value]);

  return (
    <div
      className={`block [&_svg]:h-full [&_svg]:w-full ${className}`}
      style={{ width: size, height: size }}
      // SVG is generated by the qrcode library from our own data — safe.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
